            save(datname, ...
  'file', ...
  'thispath', ...
  'ui_dist', ... 
  'ui_ex', ...   
  'ui_fref', ... 
  'ui_frnge_1', ...      
  'ui_frnge_2', ...      
  'ui_frnge_d', ...      
  'ui_hh_pc', ...        
  'ui_qp_pc', ...        
  'ui_qp_ww', ...        
  'ui_qs_pc', ...        
  'ui_qs_ww', ...        
  'ui_ro_pc', ...        
  'ui_ro_ww', ...        
  'ui_vp_pc', ...        
  'ui_vp_ww', ...        
  'ui_vs_pc', ...        
  'ui_vs_ww', ...        
  ... %  ---- gui_3D ----------------------------------------------------------------------------
  'BEST_ENERGIES', ...   
  'BEST_MISFITS', ...    
  'BEST_MODELS', ...     
  'BEST_SINGLE_MISFIT', ...  
  'BEST_SINGLE_MODELS', ...  
  'BREAKS', ...
  ... % Btn0                                                               
  'CW', ...
  'DISCARDS', ...            
  'DL', ...                  
  'DSP', ...                 
  'DW', ...                  
  'FDAT', ...                
  'FLAG__PC_features', ...   
  'HQEpicDistance', ...      
  'HQFocalDepth', ...        
  'HQMagnitude', ...         
  'HQRockRatio', ...         
  'HQfreq', ...              
  'LKT', ...                 
  'MDLS', ...                
  'MODELS', ...              
  'Matlab_Release', ...      
  'Misfit_curve_term_w', ... 
  'Misfit_slope_term_w', ... 
  'Misfit_vs_Iter', ...      
  'NresultsToKeep', ...      
  'Nrowa', ...               
  'QHspec', ...              
  'QPList', ... % (3D)
  'QSList', ... % (3D)
  'RCT', ...                 
  'REFERENCE_MODEL_dH', ...  
  'REFERENCE_MODEL_zpoints', ...    
  'ROList', ... % (3D)
  'S', ...                          
  'SN_centralval', ...              
  'SN_dtamsf', ...                  
  'SN_parname', ...                 
  'SN_parscale', ...                
  'SN_xscale', ...                  
  'STORED_1d_daf_fits', ...         
  'STORED_1d_hh_fits', ...            
  'STORED_1d_qp_fits', ...            
  'STORED_1d_qs_fits', ...            
  'STORED_1d_ro_fits', ...            
  'STORED_1d_vp_fits', ...            
  'STORED_1d_vs_fits', ...            
  'STORED_2d_daf_fits', ...           
  'STORED_2d_hh_fits', ...            
  'STORED_2d_qp_fits', ...            
  'STORED_2d_qs_fits', ...            
  'STORED_2d_ro_fits', ...            
  'STORED_2d_vp_fits', ...            
  'STORED_2d_vs_fits', ...            
  'STORED_RESULTS_1d_misfit', ...     
  'STORED_RESULTS_2d_misfit', ...     
  'STORED_RESULTS_2d_misfit_profile', ...
  'SURVEYS', ...                         
  ... % Slider0     (3D)                                                       
  ... % Slider0b    (3D)                                                           
  ... % Slider1     (3D)                                                            
  ... % Slider1b    (3D)                                                           
  ... % Slider2     (3D)                                                            
  ... % Slider2b    (3D)                                                           
  ... % 'T2_P1_global_it_count', ...           
  ... % 'T2_P1_max_it', ...                    
  ... % 'T3_P1_inv', ...                       
  ... % 'T3_P1_invSW', ...                     
  ... % 'T3_P1_it_count', ...                  
  ... % 'T3_P1_max_it', ...                    
  ... % 'T3_P1_txt', ...                       
  ... % 'T3_p1_revert', ...
  ...                  
  ... % 'T5_P1_txtx', ...                    
  ... % 'T5_P1_txty', ...                    
  ... % 'T6_P1_txtx', ...                    
  'TO_INVERT', ...                     
  'VPList', ... % (3D)                     
  'VSList', ... % (3D)                            
  'X1', ...                            
  'X2', ...                            
  'ZZList', ... % (3D)                            
  ... % ans                          
  'appname', ...                       
  'basevalue', ...                     
  'basevaluew', ...                    
  'bedrock', ...                       
  'best_FDAT', ...                     
  'beta_stuff_enable_status', ...      
  ...    
  'conf_1d_to_show_x', ...             
  'conf_1d_to_show_y', ...             
  'confidence_colormap', ...           
  'curve_plotmode', ...               
  'curve_weights_plotmode', ...       
  'cutplanes', ... % (3D)                         
  'data_1d_to_show', ...              
  'datafile_columns', ...             
  'datafile_separator', ...           
  'default_colormap', ...             
  'depth_weights_plotmode', ...       
  'dh', ...
  'dim', ... % (3D)                               
  'dw', ...                           
  'dx', ...                           
  ... % %   'eh52', ...                     
  ... % %   'eh52_childs', ...              
  'enable_menu', ...                  
  'fontsizeis', ...                   
  'gapx', ...                         
  'global_inversion_step', ...      
  ... % %   h0                                                         
  ... % %   h1                                                         
  ... % %   h10                                                        
  ... % %   h5                                                         
  ... % %   h51                                                        
  ... % %   h52                                                        
  ... % %   h5_1                                                       
  ... % %   h7                                                         
  ... % %   hAx_1d_confidence                                          
  ... % %   hAx_1dprof                                                 
  ... % %   hAx_1dprof_hcmenu                                          
  ... % %   hAx_2Dprof                                                 
  ... % %   hAx_2dprof_hcmenu                                          
  ... % %   hAx_MvsIT                                                  
  ... % %   hAx_MvsIT_hcmenu                                           
  ... % %   hAx_cnf_hcmenu                                             
  ... % %   hAx_cwf                                                    
  ... % %   hAx_cwf_hcmenu                                             
  ... % %   hAx_dat                                                    
  ... % %   hAx_dat_hcmenu                                             
  ... % %   hAx_dwf                                                    
  ... % %   hAx_dwf_hcmenu                                             
  ... % %   hAx_geo                                                    
  ... % %   hAx_geo_hcmenu                                             
  ... % %   hAx_sensitivity                                            
  ... % %   hAx_sns_hcmenu                                             
  ... % %   hRand                                                      
  ... % %   hT2_P1                                                     
  ... % %   hT2_P2                                                     
  ... % %   hT2_P3                                                     
  ... % %   hT3_P1                                                     
  ... % %   hT3_P2                                                     
  ... % %   hT3_P3                                                     
  ... % %   hT3_P4                                                     
  ... % %   hT4_P1                                                     
  ... % %   hT4_P2                                                     
  ... % %   hT5_PA                                                     
  ... % %   hT5_PB                                                     
  ... % %   hT5_PC                                                     
  ... % %   hT5_PD                                                     
  ... % %   hT6_PA                                                     
  ... % %   hT6_PC                                                     
  ... % %   hTabGroup                                                  
  ... % %   hTab_1d_viewer                                             
  ... % %   hTab_2d_viewer                                             
  ... % %   hTab_Confidenc                                             
  ... % %   hTab_Inversion                                             
  ... % %   hTab_Sensitivt                                             
  ... % %   hTab_mod                                                   
  ... % %   hTab_mod_cnames                                    
  ... % %   hTab_mod_hcmenu                                            
  ... % %   h_1d_next                                                  
  ... % %   h_1d_prev                                                  
  ... % %   h_dscale                                                   
  ... % %   h_ex_val                                                   
  ... % %   h_fref_val                                                 
  ... % %   h_fwd_sw                                                   
  ... % %   h_gui                                                      
  ... % %   h_hh_val                                                   
  ... % %   h_qp_val                                                   
  ... % %   h_qp_w                                                     
  ... % %   h_qs_val                                                   
  ... % %   h_qs_w                                                     
  ... % %   h_realtime                                                 
  ... % %   h_ro_val                                                   
  ... % %   h_ro_w                                                     
  ... % %   h_scale_max                                                
  ... % %   h_scale_min
  ... % %   h_view_rotation       (3D)
  ... % %   h_vp_val                                                   
  ... % %   h_vp_w                                                     
  ... % %   h_vs_val                                                   
  ... % %   h_vs_w                                                     
  ... % %   hconf_nlevels                                              
  ... % %   hconf_nsmooth                                              
  ... % %   hconf_xlay                                                 
  ... % %   hconf_xprop                                                
  ... % %   hconf_ylay                                                 
  ... % %   hconf_yprop                                                
  ... % %   hsns_bound                                                 
  ... % %   hsns_nlevels                                               
  ... % %   hsns_step                                                  
  ... % %   hsns_xlay                                                  
  ... % %   hsns_xprop                                                 
  'i', ...                                                         
  'id', ...                                     
  'independent_optimiazation_cicles', ...       
  'init_single_FDAT', ...                       
  'init_value__dscale', ...                     
  'init_value__fref', ...                       
  'init_value__max_scale', ...                  
  'init_value__min_scale', ...                  
  'ixmax_id', ...                                                   
  'ixmin_id', ...                                                   
  'last_FDAT', ...                              
  'last_MDLS', ...                              
  'last_log_number', ...                                            
  'last_project_name', ...                      
  'last_single_FDAT', ...                       
  'last_single_MDL', ...                        
  'lsmooth', ...                                                    
  'main_b', ...                                                     
  'main_h', ...                                                    
  'main_l', ...                                                     
  'main_scale', ...                             
  'main_w', ...                                                     
  'max_H', ...                                                      
  'max_lat_dH', ...                                                 
  'max_lat_dQp', ...                                                
  'max_lat_dQs', ...                                                
  'max_lat_dRo', ...                                                
  'max_lat_dVp', ...                                                
  'max_lat_dVs', ...                                                
  'max_qp_qs_ratio', ...                                            
  'max_qs', ...                                                     
  'max_ro', ...                                                     
  'max_vp_vs_ratio', ...                                            
  'min_H', ...                                                      
  'min_qp_qs_ratio', ...                                            
  'min_qs', ...                                                     
  'min_ro', ...                                                     
  'min_vp_vs_ratio', ...                                            
  'min_vs', ...                                                     
  'misfit_over_sumweight', ...             
  'modl_FDAT', ...                                                    
  'modl_FDATSW', ...                                                  
  'n', ...                                                          
  'n_depth_levels', ...                                             
  'ndegfree', ...                                                   
  'nlaya', ...                                                      
  'nlayb', ...                                                      
  'nlvl', ...                                                       
  'nx_ticks', ...
  'ny_ticks', ...                                %(3D)                                                           
  'nz_ticks', ...                                                   
  'objh', ...                                                       
  'objn', ...                                                       
  'objw', ...                                                       
  'objx', ...                                                       
  'objy', ...                              
  'pos_axes', ...                                                   
  'pos_axes2', ...                                                  
  'pos_axis', ...                                                   
  'pos_panel', ...                                                  
  'pos_table', ...                                                  
  'poten', ...                                                     
  'prev_BEST_SINGLE_MISFIT', ...           
  'prev_BEST_SINGLE_MODELS', ...                                      
  'prev_MDLS', ...                                                    
  'prev_best_FDAT', ...                                               
  'prev_single_it', ...
  'profile_ids', ... % (3D)                                                        
  'profile_line', ... % (3D)                                                       
  'property_1d_to_show', ...                                        
  'property_23d_to_show', ...     %(3D)
  'r_distance_from_profile', ...  %(3D)
  'r_reciprocicity', ...          %(3D)
  'receiver_locations', ...       %(3D)
  'row', ...
  'sensitivity_colormap', ...               
  'smoothing_radius', ...                                           
  'smoothing_strategy', ...                                         
  'sns_1d_to_show', ...                                             
  'str', ...                                
  'sw_nmodes', ...                                                  
  'sw_nsmooth', ...                                                 
  'vala', ...                                                       
  'valb', ...                                                       
  'var1', ...                                                       
  'var2', ...                                                       
  'version', ...                              
  'vfst_MDLS', ...                                                    
  'view_max_scale', ...                                             
  'view_min_scale', ...
  'viewerview', ...                              %(3D)
  'weight_curv', ...                          
  'weight_dpth', ...                          
  'working_folder', ...                       
  'x', ...                                                          
  'xpositions', ...                           
  'zlevels');
