function Pfunction__publish_gui(h_gui,h_menuCredits,appname,version)
%% Copyright 2015 by Samuel Bignardi.
%
% This file is part of the program OpenHVSR-Inversion.
%
% OpenHVSR-Inversion is free software: you can redistribute it and/or modify
% it under the terms of the GNU General Public License as published by
% the Free Software Foundation, either version 3 of the License, or
% (at your option) any later version.
%
% OpenHVSR-Inversion is distributed in the hope that it will be useful,
% but WITHOUT ANY WARRANTY; without even the implied warranty of
% You should have received a copy of the GNU General Public License
% along with OpenHVSR-Processing Toolkit.  If not, see <http://www.gnu.org/licenses/>.
%
%
%    
          
    Message =     ['Copyright 2015 by Samuel Bignardi                                         '; ...
                   'www.samuelbignardi.com                                                    '; ...
                   '                                                                          '; ...
                   'Distributed under the GNU GPL Licence, see the attached "COPYING" file.   '; ...
                   '                                                                          '; ...
                   'If you use this software for research purposes please cite:               '; ...
                   '                                                                          '; ...
                   'Bignardi,S.; Yezzi,A.J.; Fiussello,S. Comelli,A. (2018)                   '; ...
                   'OpenHVSR - Processing toolkit: Enhanced HVSR processing of distributed    '; ...
                   'microtremor measurements and spatial variation of their informative       '; ...
                   'content. Computers & Geosciences, 120, pp 10-20.                          '; ...
                   'DOI: 10.1016/j.cageo.2018.07.006                                          '; ...
                   '                                                                          '; ...
                   'Bignardi,S. (2017) The uncertainty of estimating the thickness of soft    '; ...
                   'sediments with the HVSR method: A computational point of view on weak     '; ...
                   'lateral variations. Journal of Applied Geophysics, Vol. 145, pp. 28-38.   '; ...
                   'DOI: 10.1016/j.jappgeo.2017.07.017                                        '; ...
                   '                                                                          '; ...
                   'Bignardi,S.; Mantovani,A.; Abu Zeid,N.;(2016).                            '; ...  
                   'OpenHVSR: imaging the subsurface 2D/3D elastic properties through multiple'; ...
                   'HVSR modeling and inversion. Computers & Geosciences.                     '; ...
                   'DOI: 10.1016/j.cageo.2016.05.009                                          '; ...
                   '                                                                          '; ...
                   'Abu Zeid,N.; Corradini,E.; Bignardi,S.; Nizzo,V.; Santarato,G. (2017)     '; ...
                   'The passive seismic technique "HVSR" as a reconnaissance tool for mapping '; ...
                   'paleo-soils: the case of the Pilastri archaeological site, Northern Italy '; ...
                   'Archaeological Prospection. DOI: 10.1002/arp.1568                         '; ...
                   '                                                                          '; ...
                   'Bignardi,S.; Yezzi,A.J.; Fiussello,S. (2018). Free and improved computer  '; ...
                   'codes for hvsr processing and inversions. 31st Annual Symposium on the    '; ...
                   'Application of Geophysics to Engineering and Environmental Problems       '; ...
                   '(SAGEEP 2018)                                                             '; ...
                   '                                                                          '; ...
                   'Abu Zeid,N.; Bignardi,S.; Santarato,G.; Peresani,M. (2017). Exploring the '; ...
                   'paleolithic cave of Fumane (Italy): Geophysical methods as planning tool  '; ...
                   'for archaeology. SEG Technical Program Expanded Abstracts 2017:           '; ...
                   'pp. 5125-5129. DOI: 10.1190/segam2017-17729320.1                          '; ...
                   '                                                                          '; ...
                   'Abu Zeid,N.; Corradini,E.; Bignardi,S.; Santarato,S. (2016) Unusual       '; ...
                   'Geophysical Techniques in Archaeology - HVSR and Induced Polarization, A  '; ...
                   'Case History. Near Surface Geoscience 2016 - 22nd European Meeting of     '; ...
                   'Environmental and Engineering Geophysics                                  '; ...
                   '                                                                          '; ...
                   'Herak,M, (2008). ModelHVSR, A Matlab tool to model horizontal-to-vertical '; ...
                   'spectral ratio of ambient noise. Computers & Geosciences                  '; ...
                   'vol. 34, pp 1514-1526.                                                    '; ...
                   '                                                                          '; ...
                   'E. Lunedei and D. Albarello. Theoretical hvsr curves from full waveeld   '; ...
                   'modelling of ambient vibrations in a weakly dissipative layered earth.    '; ...
                   'Geophys. J. Int., 181:10931108, 2010.                                    '; ...
                   '                                                                          '; ...
                   'NOTES:                                                                    '; ...
                   '  For any question, suggestion or bug fix, please contact me at the       '; ...
                   '  following email:sedysen@gmail.com                                       '; ...
                   '                  samuel.bignardi@unife.it                                '];
    set(h_menuCredits,'UserData',Message);
               
    set(h_menuCredits,'UserData',Message);
    
    set(h_gui,  'Name',strcat(appname,'-',version) )
    set(h_gui   ,'Visible','on');% Make the GUI visible.
    
    %msgHandle = msgbox(Message,'CREDITS:');


%warning('FIX THE CREDITS MESSAGE')

    
end
